name: Build

on:
  push:
    branches:
      - '**'

jobs:

  build:
    name: Build
    runs-on: macos-latest
    steps:
      - name: brew pull & reset & tap
        run: |
          brew update-reset "$(brew --repository)"
          brew tap mdogan/zulu
          brew update-reset "$(brew --repository homebrew/cask)"
          brew update-reset "$(brew --repository mdogan/zulu)"
        env:
          HOMEBREW_COLOR: 1
          HOMEBREW_DEVELOPER: 1

      - name: install jdk7
        run: brew cask install zulu-jdk7
        env:
          HOMEBREW_COLOR: 1
          HOMEBREW_DEVELOPER: 1
