name: Build

on:
  push:
    branches:
      - '**'

jobs:

  build:
    name: Build
    runs-on: macos-latest
    steps:
      - name: brew pull & reset & tap
        run: |
          brew update-reset "$(brew --repository)"
          brew tap mdogan/zulu
          brew update-reset "$(brew --repository homebrew/cask)"
          brew update-reset "$(brew --repository mdogan/zulu)"
        env:
          HOMEBREW_COLOR: 1
          HOMEBREW_DEVELOPER: 1

      - name: install jdk7
        run: brew cask install zulu-jdk7
        env:
          HOMEBREW_COLOR: 1
          HOMEBREW_DEVELOPER: 1

      - name: install jdk8
        run: brew cask install zulu-jdk8
        env:
          HOMEBREW_COLOR: 1
          HOMEBREW_DEVELOPER: 1

      - name: install jdk11
        run: brew cask install zulu-jdk11
        env:
          HOMEBREW_COLOR: 1
          HOMEBREW_DEVELOPER: 1

      - name: install jdk12
        run: brew cask install zulu-jdk12
        env:
          HOMEBREW_COLOR: 1
          HOMEBREW_DEVELOPER: 1

      - name: install jdk13
        run: brew cask install zulu-jdk13
        env:
          HOMEBREW_COLOR: 1
          HOMEBREW_DEVELOPER: 1

      - name: install jdk14
        run: brew cask install zulu-jdk14
        env:
          HOMEBREW_COLOR: 1
          HOMEBREW_DEVELOPER: 1

      - name: install jdk15ea
        run: brew cask install zulu-jdk15ea
        env:
          HOMEBREW_COLOR: 1
          HOMEBREW_DEVELOPER: 1

      - name: install mission control
        run: brew cask install zulu-mc
        env:
          HOMEBREW_COLOR: 1
          HOMEBREW_DEVELOPER: 1
